import React, { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Form from "@/components/form"
import { APPLICANT_FORM_BY_PERSONID, OLEVEL_GRADE, OLEVEL_SUBJECT, OLEVEL_TYPE } from "../../../pages/api/queries/applicant";
import { useMutation, useQuery, useLazyQuery } from '@apollo/client';
import Decrypt from "../../../components/decrypt";
import Encrypt from "../../../components/encrypt";
import Spinner from "../../../components/spinner";

export default function FillForm() {
    const [isLoadingData, setisLoadingData] = useState(true);
    const [formResponse, setformResponse] = useState({})
    const [olevelSubjects, setolevelSubjects] = useState("");
    const [olevelGrades, setolevelGrades] = useState("");
    const [olevelTypes, setolevelTypes] = useState("");
    const [fillFormData, { loading: fillFormDataLoad, error: fillFormDataError, data: fillFormDataData }] = useLazyQuery(APPLICANT_FORM_BY_PERSONID);

    const [OlevelGrade, { loading: OlevelGradeLoad, error: OlevelGradeError, data: OlevelGradeData }] = useLazyQuery(OLEVEL_GRADE);
    const [OlevelSubject, { loading: OlevelSubjectLoad, error: OlevelSubjectError, data: OlevelSubjectData }] = useLazyQuery(OLEVEL_SUBJECT);
    const [OlevelType, { loading: OlevelTypeLoad, error: OlevelTypeError, data: OlevelTypeData }] = useLazyQuery(OLEVEL_TYPE);
    const router = useRouter();
    const [invoice, setinvoice] = useState('')
    // setinvoice(router.query.formid);
    // console.log(no, "invoice no")
    useEffect(() => {
        //const no = router.query.formid;
        // console.log(no, "router no")
        // console.log(router.query, "query")
        getForm(router.query.formid);
    }, [router.query.formid]);
    const getForm = async (no) => {
        if (no !== 'undefined' && no !== null && no !== '') {
            console.log(no, " invoice nnnnnnnn")
            const formDataObject = await fillFormData({
                variables: {
                    invoicenumber: no
                }
            });
            if (formDataObject?.data !== null) {
                setformResponse(formDataObject?.data);
                console.log(formDataObject?.data, " Form Type responses")


            }
            const subjects = await OlevelSubject();
            setolevelSubjects(subjects?.data?.gellAllOLevelSubject);
            const grades = await OlevelGrade();
            setolevelGrades(grades?.data?.gellAllOLevelGrade);
            console.log(grades?.data, subjects?.data, "loaded data aaaa")
            const olevelTypesList = await OlevelType();
            console.log(olevelTypesList, "olevelTypesList .....")
            const types = [];

            // Generate years from 1999 to the current year
            for (let year = 0; year <= olevelTypesList?.data?.gellAllOLevelType.length - 1; year++) {
                console.log(olevelTypesList?.data?.gellAllOLevelType[year]?.name, year, "loop")
                if (olevelTypesList?.data?.gellAllOLevelType[year]?.name !== null && olevelTypesList?.data?.gellAllOLevelType[year]?.name !== 'undefined') {
                    types.push(olevelTypesList?.data?.gellAllOLevelType[year]?.name);
                }
            }
            console.log(types, "yearss s sjbcjd olevele")
            setolevelTypes(types)
            setisLoadingData(false)
        }

    }
    var data = {
        "data": {
            "applicantForm": {
                "mainPages": [
                    {
                        "pageId": 31,
                        "pageName": "Page 1",
                        "programmeId": 1,
                        "programmeName": "Regular",
                        "sessionId": 32,
                        "sessionName": "2022/2023",
                        "sections": [
                            {
                                "sectionId": 102,
                                "sectionName": "Bio Data",
                                "fieldDetails": [
                                    {
                                        "id": 102,
                                        "input_type": "text",
                                        "label": "Surname",
                                        "list": null,
                                        "required": null,
                                        "response": "Obinna",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": true
                                    },
                                    {
                                        "id": 103,
                                        "input_type": "text",
                                        "label": "First Name",
                                        "list": null,
                                        "required": null,
                                        "response": "Uche",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": true
                                    },
                                    {
                                        "id": 104,
                                        "input_type": "text",
                                        "label": "Other Name",
                                        "list": null,
                                        "required": null,
                                        "response": "Emma",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": true
                                    },
                                    {
                                        "id": 105,
                                        "input_type": "select",
                                        "label": "Sex",
                                        "list": [
                                            "Male",
                                            "Female"
                                        ],
                                        "required": null,
                                        "response": "Male",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 106,
                                        "input_type": "date",
                                        "label": "Date of Birth",
                                        "list": null,
                                        "required": null,
                                        "response": "04-10-1995",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 107,
                                        "input_type": "select",
                                        "label": "State",
                                        "list": [
                                            "ABIA",
                                            "ADAMAWA",
                                            "AKWA IBOM",
                                            "ANAMBRA",
                                            "BAUCHI",
                                            "BENUE",
                                            "BORNU",
                                            "BAYELSA",
                                            "CROSS RIVERS",
                                            "DELTA",
                                            "EBONYI",
                                            "EDO",
                                            "ENUGU",
                                            "EKITI",
                                            "FEDERAL CAPITAL",
                                            "GOMBE",
                                            "IMO",
                                            "JIGAWA",
                                            "KEBBI",
                                            "KADUNA",
                                            "KOGI",
                                            "KANO",
                                            "KATSINA",
                                            "KWARA",
                                            "LAGOS",
                                            "NIGER",
                                            "NASSARAWA",
                                            "ONDO",
                                            "OGUN",
                                            "OSUN",
                                            "NON-NIGERIAN",
                                            "OYO",
                                            "PLATEAU",
                                            "RIVERS",
                                            "SOKOTO",
                                            "TARABA",
                                            "YOBE"
                                        ],
                                        "required": null,
                                        "response": "EBONYI",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": true
                                    },
                                    {
                                        "id": 108,
                                        "input_type": "select",
                                        "label": "Local government",
                                        "list": [
                                            "Abakaliki",
                                            "Afikpo-North",
                                            "Afikpo-South",
                                            "Aliero",
                                            "Arewa-Dandi",
                                            "Argungu",
                                            "Augie",
                                            "Bagudo",
                                            "Birnin-Kebbi",
                                            "Bunza",
                                            "Dandi",
                                            "Ebonyi Local Government Area",
                                            "Ezza-North",
                                            "Ezza-South",
                                            "Fakai",
                                            "Gwandu",
                                            "Ikwo",
                                            "Ishielu",
                                            "Ivo",
                                            "Izzi",
                                            "Jega",
                                            "Kalgo",
                                            "Koko/Besse",
                                            "Maiyama",
                                            "Ngaski",
                                            "Ohaozara",
                                            "Ohaukwu",
                                            "Onicha",
                                            "Sakaba",
                                            "Shanga",
                                            "Suru, Nigeria",
                                            "Wasagu/Danko",
                                            "Yauri, Nigeria",
                                            "Zuru"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 109,
                                        "input_type": "text",
                                        "label": "HomeTown",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 110,
                                        "input_type": "number",
                                        "label": "Mobile Phonee",
                                        "list": null,
                                        "required": null,
                                        "response": "09070899207334",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": true
                                    },
                                    {
                                        "id": 111,
                                        "input_type": "text",
                                        "label": "Email",
                                        "list": null,
                                        "required": null,
                                        "response": "iknowyouarecomingcom",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": true
                                    },
                                    {
                                        "id": 112,
                                        "input_type": "select",
                                        "label": "Religion",
                                        "list": [
                                            "Christianity",
                                            "Islam",
                                            "Hinduism",
                                            "Buddhism",
                                            "Sikhism",
                                            "Judaism",
                                            "Bahá'í Faith",
                                            "Jainism",
                                            "Shinto",
                                            "Taoism",
                                            "Zoroastrianism",
                                            "Confucianism",
                                            "Animism",
                                            "African Traditional Religions",
                                            "Native American Religions",
                                            "Rastafari",
                                            "Scientism",
                                            "Atheism",
                                            "Agnosticism"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 113,
                                        "input_type": "text",
                                        "label": "Permanent Address",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 114,
                                        "input_type": "select",
                                        "label": "Disability",
                                        "list": [
                                            "None",
                                            "Other"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 115,
                                        "input_type": "text",
                                        "label": "If other Specify",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 116,
                                        "input_type": "text",
                                        "label": "Extra-Curricular Activities e.g (Sports/Hobbies)",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 34,
                                        "isReadonly": false
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "pageId": 32,
                        "pageName": "Page 2",
                        "programmeId": 1,
                        "programmeName": "Regular",
                        "sessionId": 32,
                        "sessionName": "2022/2023",
                        "sections": [
                            {
                                "sectionId": 117,
                                "sectionName": "Next of Kin",
                                "fieldDetails": [
                                    {
                                        "id": 117,
                                        "input_type": "text",
                                        "label": "Next of Kin's Name",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 35,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 118,
                                        "input_type": "text",
                                        "label": "Next of Kin's Address",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 35,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 119,
                                        "input_type": "select",
                                        "label": "Next of Kin's Relationship",
                                        "list": [
                                            "Father",
                                            "Mother",
                                            "Brother",
                                            "Sister",
                                            "Cousin",
                                            "Nephew",
                                            "Uncle",
                                            "Niece",
                                            "Aunt",
                                            "Grand Father",
                                            "Grand Mother",
                                            "Self",
                                            "Husband",
                                            "Wife",
                                            "Son",
                                            "Daughter"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 35,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 120,
                                        "input_type": "number",
                                        "label": "Next of Kin's Mobile Phone",
                                        "list": null,
                                        "required": null,
                                        "response": "09070899207334",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 35,
                                        "isReadonly": true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "pageId": 33,
                        "pageName": "Page 3(O-level Result)",
                        "programmeId": 1,
                        "programmeName": "Regular",
                        "sessionId": 32,
                        "sessionName": "2022/2023",
                        "sections": [
                            {
                                "sectionId": 121,
                                "sectionName": "O-Level Result",
                                "fieldDetails": [
                                    {
                                        "id": 121,
                                        "input_type": "text",
                                        "label": "O-Level",
                                        "list": [
                                            "100 Level"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 36,
                                        "isReadonly": false
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "pageId": 34,
                        "pageName": "Page 4",
                        "programmeId": 1,
                        "programmeName": "Regular",
                        "sessionId": 32,
                        "sessionName": "2022/2023",
                        "sections": [
                            {
                                "sectionId": 122,
                                "sectionName": "UTME Details/Mode of Reference",
                                "fieldDetails": [
                                    {
                                        "id": 122,
                                        "input_type": "text",
                                        "label": "Jamb Registration No",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 37,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 123,
                                        "input_type": "text",
                                        "label": "Jamb Score",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 37,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 124,
                                        "input_type": "select",
                                        "label": "Choice",
                                        "list": [
                                            "First",
                                            "Second",
                                            "Third"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 37,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 125,
                                        "input_type": "select",
                                        "label": "First Subject",
                                        "list": [
                                            "English",
                                            "Mathematics",
                                            "Physics",
                                            "Chemistry",
                                            "Agriculture",
                                            "Biology",
                                            "Economics",
                                            "Food and Nutrition",
                                            "Commerce",
                                            "Government",
                                            "Insurance",
                                            "Christian Religious Knowledge",
                                            "Dying and Blishing",
                                            "Account",
                                            "Literature In English",
                                            "Integrated Science",
                                            "Civic Education",
                                            "Igbo Language",
                                            "French",
                                            "Home Economics",
                                            "Computer",
                                            "Creative and Cultural Art",
                                            "Intro Technology",
                                            "Music",
                                            "Social Studies",
                                            "Business Studies",
                                            "Basic Technology",
                                            "General Paper",
                                            "Basic Science",
                                            "Physical and Health Education",
                                            "Fine Arts",
                                            "Data Processing",
                                            "Financial Accounting",
                                            "Geography",
                                            "Painting and Decoration",
                                            "Catering Craft",
                                            "Moral Instruction",
                                            "Business Method",
                                            "Principles of Accounts",
                                            "Office Practice",
                                            "History",
                                            "Typewriting",
                                            "Shorthand",
                                            "Basic Electricity",
                                            "Technical Drawing",
                                            "Further Mathematics",
                                            "Book Keeping & Principles of Accounting",
                                            "Health Science",
                                            "Wood Work",
                                            "Basic Electronics",
                                            "Auto Mechanics",
                                            "Metal Work",
                                            "Home Management",
                                            "AGRICULTURAL EQUIPMENT MECHANICS WORKS (INTRODUCTI",
                                            "BASKETRY",
                                            "AGRICULTURAL EQUIPMENT MECHANICS WORKS (TRACTOR SY",
                                            "ANIMAL HUSBANDARY",
                                            "APPLIED ELECTRICITY",
                                            "APPLIED ELECTRICITY AND AUTOMOBILE",
                                            "ARABIC",
                                            "ARITHMETIC PROCESS",
                                            "AUTO ELECTRICAL WORKS",
                                            "AUTOMOBILE ELECTRICAL WORKS",
                                            "BLOCKLAYING, BRICKLAYING AND CONCRETING",
                                            "BUILDING CONSTRUCTION",
                                            "BUILDING/ENGINEERING DRAWING",
                                            "BUSINESS MANAGEMENT",
                                            "CARPENTRY AND JOINERY",
                                            "CERAMICS",
                                            "CERAMICS (CERAMICS DESIGN)",
                                            "CHRISTIAN RELIGIOUS STUDIES",
                                            "CIVIC EDUCATION",
                                            "CLERICAL OFFICE DUTIES",
                                            "CLOTHING AND TEXTILE",
                                            "COMPUTER CRAFT STUDIES",
                                            "COSMETOLOGY",
                                            "CROP HUSBANDARY AND HORTICULTURE",
                                            "DRAUGHTMANSHIP CRAFT PRACTICE (DRAUGHTMANSHIP)",
                                            "ELECTRICAL INSTALLATION AND MAINTENANCE WORK",
                                            "ELECTRONICS",
                                            "ELECTRONICS WORKS",
                                            "ENGINEERING SCIENCE",
                                            "FABRICATION AND WEILDING",
                                            "FISHERIES",
                                            "FITTING DRILLING AND GRINDING",
                                            "FORESTERY",
                                            "FOUNDRY CRAFT PRACTICE",
                                            "FURNITURE MAKING",
                                            "GENERAL METAL WORK",
                                            "GENERAL WOOD WORK",
                                            "GRAPHIC ART (GRAPHIC DESIGN)",
                                            "GRAPHIC DESIGN",
                                            "HAUSA LANGUAGE",
                                            "HISTORY",
                                            "INFORMATION COMMUNICATION TECHNOLOGY (ICT)",
                                            "INSTRUMENT MECHANICS WORKS",
                                            "INTRODUCTION TO BUILDING CONSTRUCTION",
                                            "ISLAMIC STUDIES",
                                            "JEWELLERY",
                                            "",
                                            "LADIES GARMENT MAKING (GARMENT CONSTRUCTION AND FI",
                                            "LEATHER TRADES (FOOTWEAR MANUFACTURE)",
                                            "LEATHER TRADES (LEATHER GOODS MANUFACTURE)",
                                            "LEATHER TRADES (LEATHER TRANNING)",
                                            "LEATHERWORK",
                                            "LIGHT VEHICLE BODY REPAIR WORKS",
                                            "MACHING WOOD WORKING",
                                            "MANAGEMENT IN-LIVING",
                                            "MARINE ENGINEERING CRAFT",
                                            "MARINE ENGINEERING CRAFT PRACTICE",
                                            "MECHANICAL ENGINEERING CRAFT PRACTICE",
                                            "MEDICAL ENGINEERING CRAFT PRACTICE",
                                            "MEN'S GARMENT MAKING (GARMENT CONSTRUCTION AND FIN",
                                            "MOTOR VEHICLE MECHANICS WORK",
                                            "PHOTOGRAPHIC PRACTICE",
                                            "PHYSICAL EDUCATION",
                                            "PICTURE MAKING",
                                            "PLUMBING AND PIPE FITTING",
                                            "PRATICAL TEACHING",
                                            "PRINCIPLE & PRACTICE OF  EDUCATION",
                                            "PRINCIPLES & PRACTICE OF EDUCATION",
                                            "PRINTING CRAFT PRACTICE",
                                            "REFRIGERATION AND AIR-CONDITIONING",
                                            "SALESMANSHIP",
                                            "SCULPTURE",
                                            "SECRETARIAL STUDIES",
                                            "SHIP CRAFT PRACTICE",
                                            "TEXTILE TRADE (BLEACHING, DYEING AND FINISHING)",
                                            "TEXTILE TRADE (SPINNING)",
                                            "TEXTILE TRADE (WEAVING)",
                                            "TEXTILE TRADES (SURFACE DESIGN AND TEXTILE PRINTIN",
                                            "TEXTILES",
                                            "TOURISM",
                                            "TURNING MILLING AND SHAPING",
                                            "VEHICLE BODY BUILDING",
                                            "VISUAL ART",
                                            "YORUBA LANGUAGE",
                                            "Marketing"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 37,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 126,
                                        "input_type": "select",
                                        "label": "Second Subject",
                                        "list": [
                                            "English",
                                            "Mathematics",
                                            "Physics",
                                            "Chemistry",
                                            "Agriculture",
                                            "Biology",
                                            "Economics",
                                            "Food and Nutrition",
                                            "Commerce",
                                            "Government",
                                            "Insurance",
                                            "Christian Religious Knowledge",
                                            "Dying and Blishing",
                                            "Account",
                                            "Literature In English",
                                            "Integrated Science",
                                            "Civic Education",
                                            "Igbo Language",
                                            "French",
                                            "Home Economics",
                                            "Computer",
                                            "Creative and Cultural Art",
                                            "Intro Technology",
                                            "Music",
                                            "Social Studies",
                                            "Business Studies",
                                            "Basic Technology",
                                            "General Paper",
                                            "Basic Science",
                                            "Physical and Health Education",
                                            "Fine Arts",
                                            "Data Processing",
                                            "Financial Accounting",
                                            "Geography",
                                            "Painting and Decoration",
                                            "Catering Craft",
                                            "Moral Instruction",
                                            "Business Method",
                                            "Principles of Accounts",
                                            "Office Practice",
                                            "History",
                                            "Typewriting",
                                            "Shorthand",
                                            "Basic Electricity",
                                            "Technical Drawing",
                                            "Further Mathematics",
                                            "Book Keeping & Principles of Accounting",
                                            "Health Science",
                                            "Wood Work",
                                            "Basic Electronics",
                                            "Auto Mechanics",
                                            "Metal Work",
                                            "Home Management",
                                            "AGRICULTURAL EQUIPMENT MECHANICS WORKS (INTRODUCTI",
                                            "BASKETRY",
                                            "AGRICULTURAL EQUIPMENT MECHANICS WORKS (TRACTOR SY",
                                            "ANIMAL HUSBANDARY",
                                            "APPLIED ELECTRICITY",
                                            "APPLIED ELECTRICITY AND AUTOMOBILE",
                                            "ARABIC",
                                            "ARITHMETIC PROCESS",
                                            "AUTO ELECTRICAL WORKS",
                                            "AUTOMOBILE ELECTRICAL WORKS",
                                            "BLOCKLAYING, BRICKLAYING AND CONCRETING",
                                            "BUILDING CONSTRUCTION",
                                            "BUILDING/ENGINEERING DRAWING",
                                            "BUSINESS MANAGEMENT",
                                            "CARPENTRY AND JOINERY",
                                            "CERAMICS",
                                            "CERAMICS (CERAMICS DESIGN)",
                                            "CHRISTIAN RELIGIOUS STUDIES",
                                            "CIVIC EDUCATION",
                                            "CLERICAL OFFICE DUTIES",
                                            "CLOTHING AND TEXTILE",
                                            "COMPUTER CRAFT STUDIES",
                                            "COSMETOLOGY",
                                            "CROP HUSBANDARY AND HORTICULTURE",
                                            "DRAUGHTMANSHIP CRAFT PRACTICE (DRAUGHTMANSHIP)",
                                            "ELECTRICAL INSTALLATION AND MAINTENANCE WORK",
                                            "ELECTRONICS",
                                            "ELECTRONICS WORKS",
                                            "ENGINEERING SCIENCE",
                                            "FABRICATION AND WEILDING",
                                            "FISHERIES",
                                            "FITTING DRILLING AND GRINDING",
                                            "FORESTERY",
                                            "FOUNDRY CRAFT PRACTICE",
                                            "FURNITURE MAKING",
                                            "GENERAL METAL WORK",
                                            "GENERAL WOOD WORK",
                                            "GRAPHIC ART (GRAPHIC DESIGN)",
                                            "GRAPHIC DESIGN",
                                            "HAUSA LANGUAGE",
                                            "HISTORY",
                                            "INFORMATION COMMUNICATION TECHNOLOGY (ICT)",
                                            "INSTRUMENT MECHANICS WORKS",
                                            "INTRODUCTION TO BUILDING CONSTRUCTION",
                                            "ISLAMIC STUDIES",
                                            "JEWELLERY",
                                            "",
                                            "LADIES GARMENT MAKING (GARMENT CONSTRUCTION AND FI",
                                            "LEATHER TRADES (FOOTWEAR MANUFACTURE)",
                                            "LEATHER TRADES (LEATHER GOODS MANUFACTURE)",
                                            "LEATHER TRADES (LEATHER TRANNING)",
                                            "LEATHERWORK",
                                            "LIGHT VEHICLE BODY REPAIR WORKS",
                                            "MACHING WOOD WORKING",
                                            "MANAGEMENT IN-LIVING",
                                            "MARINE ENGINEERING CRAFT",
                                            "MARINE ENGINEERING CRAFT PRACTICE",
                                            "MECHANICAL ENGINEERING CRAFT PRACTICE",
                                            "MEDICAL ENGINEERING CRAFT PRACTICE",
                                            "MEN'S GARMENT MAKING (GARMENT CONSTRUCTION AND FIN",
                                            "MOTOR VEHICLE MECHANICS WORK",
                                            "PHOTOGRAPHIC PRACTICE",
                                            "PHYSICAL EDUCATION",
                                            "PICTURE MAKING",
                                            "PLUMBING AND PIPE FITTING",
                                            "PRATICAL TEACHING",
                                            "PRINCIPLE & PRACTICE OF  EDUCATION",
                                            "PRINCIPLES & PRACTICE OF EDUCATION",
                                            "PRINTING CRAFT PRACTICE",
                                            "REFRIGERATION AND AIR-CONDITIONING",
                                            "SALESMANSHIP",
                                            "SCULPTURE",
                                            "SECRETARIAL STUDIES",
                                            "SHIP CRAFT PRACTICE",
                                            "TEXTILE TRADE (BLEACHING, DYEING AND FINISHING)",
                                            "TEXTILE TRADE (SPINNING)",
                                            "TEXTILE TRADE (WEAVING)",
                                            "TEXTILE TRADES (SURFACE DESIGN AND TEXTILE PRINTIN",
                                            "TEXTILES",
                                            "TOURISM",
                                            "TURNING MILLING AND SHAPING",
                                            "VEHICLE BODY BUILDING",
                                            "VISUAL ART",
                                            "YORUBA LANGUAGE",
                                            "Marketing"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 37,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 127,
                                        "input_type": "select",
                                        "label": "Third Subject",
                                        "list": [
                                            "English",
                                            "Mathematics",
                                            "Physics",
                                            "Chemistry",
                                            "Agriculture",
                                            "Biology",
                                            "Economics",
                                            "Food and Nutrition",
                                            "Commerce",
                                            "Government",
                                            "Insurance",
                                            "Christian Religious Knowledge",
                                            "Dying and Blishing",
                                            "Account",
                                            "Literature In English",
                                            "Integrated Science",
                                            "Civic Education",
                                            "Igbo Language",
                                            "French",
                                            "Home Economics",
                                            "Computer",
                                            "Creative and Cultural Art",
                                            "Intro Technology",
                                            "Music",
                                            "Social Studies",
                                            "Business Studies",
                                            "Basic Technology",
                                            "General Paper",
                                            "Basic Science",
                                            "Physical and Health Education",
                                            "Fine Arts",
                                            "Data Processing",
                                            "Financial Accounting",
                                            "Geography",
                                            "Painting and Decoration",
                                            "Catering Craft",
                                            "Moral Instruction",
                                            "Business Method",
                                            "Principles of Accounts",
                                            "Office Practice",
                                            "History",
                                            "Typewriting",
                                            "Shorthand",
                                            "Basic Electricity",
                                            "Technical Drawing",
                                            "Further Mathematics",
                                            "Book Keeping & Principles of Accounting",
                                            "Health Science",
                                            "Wood Work",
                                            "Basic Electronics",
                                            "Auto Mechanics",
                                            "Metal Work",
                                            "Home Management",
                                            "AGRICULTURAL EQUIPMENT MECHANICS WORKS (INTRODUCTI",
                                            "BASKETRY",
                                            "AGRICULTURAL EQUIPMENT MECHANICS WORKS (TRACTOR SY",
                                            "ANIMAL HUSBANDARY",
                                            "APPLIED ELECTRICITY",
                                            "APPLIED ELECTRICITY AND AUTOMOBILE",
                                            "ARABIC",
                                            "ARITHMETIC PROCESS",
                                            "AUTO ELECTRICAL WORKS",
                                            "AUTOMOBILE ELECTRICAL WORKS",
                                            "BLOCKLAYING, BRICKLAYING AND CONCRETING",
                                            "BUILDING CONSTRUCTION",
                                            "BUILDING/ENGINEERING DRAWING",
                                            "BUSINESS MANAGEMENT",
                                            "CARPENTRY AND JOINERY",
                                            "CERAMICS",
                                            "CERAMICS (CERAMICS DESIGN)",
                                            "CHRISTIAN RELIGIOUS STUDIES",
                                            "CIVIC EDUCATION",
                                            "CLERICAL OFFICE DUTIES",
                                            "CLOTHING AND TEXTILE",
                                            "COMPUTER CRAFT STUDIES",
                                            "COSMETOLOGY",
                                            "CROP HUSBANDARY AND HORTICULTURE",
                                            "DRAUGHTMANSHIP CRAFT PRACTICE (DRAUGHTMANSHIP)",
                                            "ELECTRICAL INSTALLATION AND MAINTENANCE WORK",
                                            "ELECTRONICS",
                                            "ELECTRONICS WORKS",
                                            "ENGINEERING SCIENCE",
                                            "FABRICATION AND WEILDING",
                                            "FISHERIES",
                                            "FITTING DRILLING AND GRINDING",
                                            "FORESTERY",
                                            "FOUNDRY CRAFT PRACTICE",
                                            "FURNITURE MAKING",
                                            "GENERAL METAL WORK",
                                            "GENERAL WOOD WORK",
                                            "GRAPHIC ART (GRAPHIC DESIGN)",
                                            "GRAPHIC DESIGN",
                                            "HAUSA LANGUAGE",
                                            "HISTORY",
                                            "INFORMATION COMMUNICATION TECHNOLOGY (ICT)",
                                            "INSTRUMENT MECHANICS WORKS",
                                            "INTRODUCTION TO BUILDING CONSTRUCTION",
                                            "ISLAMIC STUDIES",
                                            "JEWELLERY",
                                            "",
                                            "LADIES GARMENT MAKING (GARMENT CONSTRUCTION AND FI",
                                            "LEATHER TRADES (FOOTWEAR MANUFACTURE)",
                                            "LEATHER TRADES (LEATHER GOODS MANUFACTURE)",
                                            "LEATHER TRADES (LEATHER TRANNING)",
                                            "LEATHERWORK",
                                            "LIGHT VEHICLE BODY REPAIR WORKS",
                                            "MACHING WOOD WORKING",
                                            "MANAGEMENT IN-LIVING",
                                            "MARINE ENGINEERING CRAFT",
                                            "MARINE ENGINEERING CRAFT PRACTICE",
                                            "MECHANICAL ENGINEERING CRAFT PRACTICE",
                                            "MEDICAL ENGINEERING CRAFT PRACTICE",
                                            "MEN'S GARMENT MAKING (GARMENT CONSTRUCTION AND FIN",
                                            "MOTOR VEHICLE MECHANICS WORK",
                                            "PHOTOGRAPHIC PRACTICE",
                                            "PHYSICAL EDUCATION",
                                            "PICTURE MAKING",
                                            "PLUMBING AND PIPE FITTING",
                                            "PRATICAL TEACHING",
                                            "PRINCIPLE & PRACTICE OF  EDUCATION",
                                            "PRINCIPLES & PRACTICE OF EDUCATION",
                                            "PRINTING CRAFT PRACTICE",
                                            "REFRIGERATION AND AIR-CONDITIONING",
                                            "SALESMANSHIP",
                                            "SCULPTURE",
                                            "SECRETARIAL STUDIES",
                                            "SHIP CRAFT PRACTICE",
                                            "TEXTILE TRADE (BLEACHING, DYEING AND FINISHING)",
                                            "TEXTILE TRADE (SPINNING)",
                                            "TEXTILE TRADE (WEAVING)",
                                            "TEXTILE TRADES (SURFACE DESIGN AND TEXTILE PRINTIN",
                                            "TEXTILES",
                                            "TOURISM",
                                            "TURNING MILLING AND SHAPING",
                                            "VEHICLE BODY BUILDING",
                                            "VISUAL ART",
                                            "YORUBA LANGUAGE",
                                            "Marketing"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 37,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 128,
                                        "input_type": "select",
                                        "label": "Fourth Subject",
                                        "list": [
                                            "English",
                                            "Mathematics",
                                            "Physics",
                                            "Chemistry",
                                            "Agriculture",
                                            "Biology",
                                            "Economics",
                                            "Food and Nutrition",
                                            "Commerce",
                                            "Government",
                                            "Insurance",
                                            "Christian Religious Knowledge",
                                            "Dying and Blishing",
                                            "Account",
                                            "Literature In English",
                                            "Integrated Science",
                                            "Civic Education",
                                            "Igbo Language",
                                            "French",
                                            "Home Economics",
                                            "Computer",
                                            "Creative and Cultural Art",
                                            "Intro Technology",
                                            "Music",
                                            "Social Studies",
                                            "Business Studies",
                                            "Basic Technology",
                                            "General Paper",
                                            "Basic Science",
                                            "Physical and Health Education",
                                            "Fine Arts",
                                            "Data Processing",
                                            "Financial Accounting",
                                            "Geography",
                                            "Painting and Decoration",
                                            "Catering Craft",
                                            "Moral Instruction",
                                            "Business Method",
                                            "Principles of Accounts",
                                            "Office Practice",
                                            "History",
                                            "Typewriting",
                                            "Shorthand",
                                            "Basic Electricity",
                                            "Technical Drawing",
                                            "Further Mathematics",
                                            "Book Keeping & Principles of Accounting",
                                            "Health Science",
                                            "Wood Work",
                                            "Basic Electronics",
                                            "Auto Mechanics",
                                            "Metal Work",
                                            "Home Management",
                                            "AGRICULTURAL EQUIPMENT MECHANICS WORKS (INTRODUCTI",
                                            "BASKETRY",
                                            "AGRICULTURAL EQUIPMENT MECHANICS WORKS (TRACTOR SY",
                                            "ANIMAL HUSBANDARY",
                                            "APPLIED ELECTRICITY",
                                            "APPLIED ELECTRICITY AND AUTOMOBILE",
                                            "ARABIC",
                                            "ARITHMETIC PROCESS",
                                            "AUTO ELECTRICAL WORKS",
                                            "AUTOMOBILE ELECTRICAL WORKS",
                                            "BLOCKLAYING, BRICKLAYING AND CONCRETING",
                                            "BUILDING CONSTRUCTION",
                                            "BUILDING/ENGINEERING DRAWING",
                                            "BUSINESS MANAGEMENT",
                                            "CARPENTRY AND JOINERY",
                                            "CERAMICS",
                                            "CERAMICS (CERAMICS DESIGN)",
                                            "CHRISTIAN RELIGIOUS STUDIES",
                                            "CIVIC EDUCATION",
                                            "CLERICAL OFFICE DUTIES",
                                            "CLOTHING AND TEXTILE",
                                            "COMPUTER CRAFT STUDIES",
                                            "COSMETOLOGY",
                                            "CROP HUSBANDARY AND HORTICULTURE",
                                            "DRAUGHTMANSHIP CRAFT PRACTICE (DRAUGHTMANSHIP)",
                                            "ELECTRICAL INSTALLATION AND MAINTENANCE WORK",
                                            "ELECTRONICS",
                                            "ELECTRONICS WORKS",
                                            "ENGINEERING SCIENCE",
                                            "FABRICATION AND WEILDING",
                                            "FISHERIES",
                                            "FITTING DRILLING AND GRINDING",
                                            "FORESTERY",
                                            "FOUNDRY CRAFT PRACTICE",
                                            "FURNITURE MAKING",
                                            "GENERAL METAL WORK",
                                            "GENERAL WOOD WORK",
                                            "GRAPHIC ART (GRAPHIC DESIGN)",
                                            "GRAPHIC DESIGN",
                                            "HAUSA LANGUAGE",
                                            "HISTORY",
                                            "INFORMATION COMMUNICATION TECHNOLOGY (ICT)",
                                            "INSTRUMENT MECHANICS WORKS",
                                            "INTRODUCTION TO BUILDING CONSTRUCTION",
                                            "ISLAMIC STUDIES",
                                            "JEWELLERY",
                                            "",
                                            "LADIES GARMENT MAKING (GARMENT CONSTRUCTION AND FI",
                                            "LEATHER TRADES (FOOTWEAR MANUFACTURE)",
                                            "LEATHER TRADES (LEATHER GOODS MANUFACTURE)",
                                            "LEATHER TRADES (LEATHER TRANNING)",
                                            "LEATHERWORK",
                                            "LIGHT VEHICLE BODY REPAIR WORKS",
                                            "MACHING WOOD WORKING",
                                            "MANAGEMENT IN-LIVING",
                                            "MARINE ENGINEERING CRAFT",
                                            "MARINE ENGINEERING CRAFT PRACTICE",
                                            "MECHANICAL ENGINEERING CRAFT PRACTICE",
                                            "MEDICAL ENGINEERING CRAFT PRACTICE",
                                            "MEN'S GARMENT MAKING (GARMENT CONSTRUCTION AND FIN",
                                            "MOTOR VEHICLE MECHANICS WORK",
                                            "PHOTOGRAPHIC PRACTICE",
                                            "PHYSICAL EDUCATION",
                                            "PICTURE MAKING",
                                            "PLUMBING AND PIPE FITTING",
                                            "PRATICAL TEACHING",
                                            "PRINCIPLE & PRACTICE OF  EDUCATION",
                                            "PRINCIPLES & PRACTICE OF EDUCATION",
                                            "PRINTING CRAFT PRACTICE",
                                            "REFRIGERATION AND AIR-CONDITIONING",
                                            "SALESMANSHIP",
                                            "SCULPTURE",
                                            "SECRETARIAL STUDIES",
                                            "SHIP CRAFT PRACTICE",
                                            "TEXTILE TRADE (BLEACHING, DYEING AND FINISHING)",
                                            "TEXTILE TRADE (SPINNING)",
                                            "TEXTILE TRADE (WEAVING)",
                                            "TEXTILE TRADES (SURFACE DESIGN AND TEXTILE PRINTIN",
                                            "TEXTILES",
                                            "TOURISM",
                                            "TURNING MILLING AND SHAPING",
                                            "VEHICLE BODY BUILDING",
                                            "VISUAL ART",
                                            "YORUBA LANGUAGE",
                                            "Marketing"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 37,
                                        "isReadonly": false
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "pageId": 35,
                        "pageName": "Page 5",
                        "programmeId": 1,
                        "programmeName": "Regular",
                        "sessionId": 32,
                        "sessionName": "2022/2023",
                        "sections": [
                            {
                                "sectionId": 129,
                                "sectionName": "Academic Details",
                                "fieldDetails": [
                                    {
                                        "id": 129,
                                        "input_type": "text",
                                        "label": "Programme",
                                        "list": [
                                            "Regular",
                                            "ND part-time",
                                            "HND ",
                                            "HND MORNING",
                                            "",
                                            "test"
                                        ],
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 38,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 130,
                                        "input_type": "text",
                                        "label": "School",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 38,
                                        "isReadonly": false
                                    },
                                    {
                                        "id": 131,
                                        "input_type": "text",
                                        "label": "Course of Study",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 38,
                                        "isReadonly": false
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "pageId": 36,
                        "pageName": "Page 6(Passport)",
                        "programmeId": 1,
                        "programmeName": "Regular",
                        "sessionId": 32,
                        "sessionName": "2022/2023",
                        "sections": [
                            {
                                "sectionId": 132,
                                "sectionName": "Passport Photograph",
                                "fieldDetails": [
                                    {
                                        "id": 132,
                                        "input_type": "text",
                                        "label": "Passport Photograph",
                                        "list": null,
                                        "required": null,
                                        "response": "",
                                        "errorMessage": null,
                                        "dynamicFormPageSectionSetupId": 39,
                                        "isReadonly": false
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "submitOlevelResult": [],
                "personId": 33,
                "personUrl": null
            }
        }
    };



    return (
        <>
            {isLoadingData ? <Spinner /> :
                <Form data={formResponse} olevelSubjectsData={olevelSubjects} olevelGradesData={olevelGrades} isPreview={false} olevelTypes={olevelTypes} />}
        </>
    )
}
